REGISTRY: {}
a2: '-0.24'
a3: '-0.299658'
args: {}
base_link: base_link
base_mount: ''
base_rpy: 0 0 0
base_xyz: 0 0 0
config_dir: /home/bam/bam_ws/src/bam_common/bam_descriptions/urdf/dummy_dh/config
config_file_name: _sku_v0.0.0_config
config_file: /home/bam/bam_ws/src/bam_common/bam_descriptions/urdf/dummy_dh/config/_sku_v0.0.0_config.yaml
d1: '0.1565'
d4: '0.0271'
d5: '0.077'
d6: '0.017'
dh:
    a2: '-0.24'
    a3: '-0.299658'
    d1: '0.1565'
    d4: '0.0271'
    d5: '0.077'
    d6: '0.017'
force_srdf_gen: 'false'
hand_mount: ''
ik_base_link: ''
ik_sol_preference: []
ik_tip: ''
ik_tip_flip: ''
info:
    calib_hash: ''
    config_key: ''
    name: ''
    sku: ''
    type: ''
    uuid: 00000000-0000-0000-0000-000000000000
    version: 0.0.0
joints: {}
links: {}
lock_joints: 'false'
named_positions: {}
plugin: none
points_of_interest: []
prefix: ''
reach_map_path: ''
reflect: '1'
root_link: world
srdf:
    loaded_from_cache: 'true'
    macro_path: ''
    newly_generated: 'false'
    path: /home/bam/bam_ws/src/bam_common/bam_descriptions/urdf/dummy_dh/config/srdf_cache/_sku_v0.0.0_config.srdf
    xacro_path: ''
trajectory_topic: ''
urdf:
    macro_path: ''
    mesh_dirs: /home/bam/bam_ws/src/bam_core
    path: ''
    xacro_path: /home/bam/bam_ws/src/bam_common/bam_descriptions/urdf/dummy_dh/dummy_dh.urdf.xacro
world_rpy: 0 0 0
world_xyz: 0 0 0
