REGISTRY: {}
base_link: base_link
description_config_file: /home/bam/bam_ws/src/bam_common/bam_descriptions/urdf/one_dof/config/one_dof_sku_v0.0.0_config.yaml
dh:
    a2: 0.0
    a3: 0.0
    d1: 0.0
    d4: 0.0
    d5: 0.0
    d6: 0.0
five_bar:
    L_c1: 0.0
    L_c2: 0.0
    L_elbow: 0.0
    L_l1: 0.0
    L_l2: 0.0
    L_shoulder: 0.0
ik_sol_preference: []
ik_tip: rotor
info:
    name: ''
    prefix: ''
    sku: '600'
    type: one_dof
    uuid: 00000000-0000-0000-0000-000000000000
    version: 0.0.0
joints:
-   can_id: 0
    hardstop_position: 0.0
    home_position: 0.0
    intial_state:
        position: 0.0
    limits:
        has_acceleration_limits: true
        has_effort_limits: true
        has_jerk_limits: true
        has_position_limits: false
        has_velocity_limits: true
        max_acceleration: 1.0
        max_effort: 1.0
        max_jerk: 1.0
        max_position: 0.0
        max_velocity: 1.0
        min_acceleration: 1.0
        min_effort: 1.0
        min_jerk: 1.0
        min_position: -0.0
        min_velocity: 1.0
    lock: false
    lock_position: 0.0
    name: joint_1
    passive: false
    physics:
        damping: 0.0
        friction: 0.0
links: []
metadata:
    created_at: 09_oct_2025_09_46pm
    created_by: ConfigBase
    version: '1.0'
reach_map_path: ''
sku: '600'
srdf:
    path: ''
    xacro_args: {}
    xacro_path: ''
trajectory_topic: trajectory_controller/follow_trajectory
urdf:
    mesh_dirs: /home/bam/bam_ws/src/bam_core
    path: ''
    xacro_args:
        arm_length: 0.6
        arm_mass: 0.272
        arm_width: 0.02
        controllers_file_path: /home/bam/bam_ws/src/bam_core/bam_core_bringup/config/controllers/one_dof_controllers.yaml
        gearbox_diameter: 0.04
        gearbox_length: 0.08
        gearbox_mass: 0.15
        mounting_angle: 0.0
        payload_diameter: 1.0e-06
        payload_distance: 0.0
        payload_mass: 0.0
        payload_thickness: 1.0e-06
        plugin: mock
        ros2_control: true
        ros_namespace: bam_GPU
        rotor_diameter: 0.05
        rotor_length: 0.1
        rotor_mass: 0.2
        transport_path: /dev/serial/by-id/usb-mjbots_fdcanusb_28B3A25D-if00
    xacro_path: /home/bam/bam_ws/src/bam_common/bam_descriptions/urdf/one_dof/one_dof.urdf.xacro
urdf_xacro_args:
    arm_length: 0.6
    arm_mass: 0.272
    arm_width: 0.02
    controllers_file_path: /home/bam/bam_ws/src/bam_core/bam_core_bringup/config/controllers/one_dof_controllers.yaml
    gearbox_diameter: 0.04
    gearbox_length: 0.08
    gearbox_mass: 0.15
    mounting_angle: 0.0
    payload_diameter: 1.0e-06
    payload_distance: 0.0
    payload_mass: 0.0
    payload_thickness: 1.0e-06
    plugin: mock
    ros2_control: true
    ros_namespace: bam_GPU
    rotor_diameter: 0.05
    rotor_length: 0.1
    rotor_mass: 0.2
    transport_path: /dev/serial/by-id/usb-mjbots_fdcanusb_28B3A25D-if00
