REGISTRY: {}
args: {}
bam_descriptions: /home/bam/bam_ws/src/bam_machine/bam/descriptions
base_link: base_link
base_mount: left_left_surface_center
base_rpy: 0 0 0.7853981633974483
base_xyz: 0.1 0.2 0
center_link: left_center
config_dir: /home/bam/bam_ws/src/bam_machine/bam/descriptions/urdf/conveyor/config
config_file_name: left_conveyor_v1_v0.0.0
config_file: /home/bam/bam_ws/src/bam_machine/bam/descriptions/urdf/conveyor/config/left_conveyor_v1_v0.0.0.yaml
force_srdf_gen: 'false'
hash_config_file: 'false'
height: '0.05'
info:
    config_key: ''
    name: conveyor
    sku: v1
    type: conveyor
    urdf_hash: ''
    uuid: ''
    version: 0.0.0
joints:
    belt_joint:
        can_id: '0'
        hardstop_position: '0.0'
        home_position: '0.0'
        initial_position: '0.0'
        limits:
            has_acceleration_limits: 'true'
            has_effort_limits: 'true'
            has_jerk_limits: 'true'
            has_position_limits: 'false'
            has_velocity_limits: 'true'
            max_acceleration: '10.0'
            max_effort: '10.0'
            max_jerk: '100.0'
            max_position: '3.141593'
            max_velocity: '10.0'
            min_acceleration: '-10.0'
            min_effort: '-10.0'
            min_jerk: '-100.0'
            min_position: '-3.141593'
            min_velocity: '-10.0'
        lock: 'false'
        lock_position: '0.0'
        mimic: 'false'
        name: left_belt_joint
        physics:
            damping: '0.0'
            friction: '0.0'
        transform:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        type: fixed
        unprefixed_name: belt_joint
    entities:
        left_left_belt_joint:
            can_id: '0'
            hardstop_position: '0.0'
            home_position: '0.0'
            initial_position: '0.0'
            limits:
                has_acceleration_limits: 'true'
                has_effort_limits: 'true'
                has_jerk_limits: 'true'
                has_position_limits: 'false'
                has_velocity_limits: 'true'
                max_acceleration: '10.0'
                max_effort: '10.0'
                max_jerk: '100.0'
                max_position: '3.141593'
                max_velocity: '10.0'
                min_acceleration: '-10.0'
                min_effort: '-10.0'
                min_jerk: '-100.0'
                min_position: '-3.141593'
                min_velocity: '-10.0'
            lock: 'false'
            lock_position: '0.0'
            mimic: 'false'
            name: left_belt_joint
            physics:
                damping: '0.0'
                friction: '0.0'
            transform:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
            type: fixed
            unprefixed_name: belt_joint
length: '2.0'
links:
    center:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'false'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'false'
        name: left_center
        scene_obj_collision: 'false'
        unprefixed_name: center
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
    entities:
        left_left_center:
            collision_geometry_size: 0.0 0.0 0.0
            collision_geometry_type: box
            collision_mesh_path: ''
            collision_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
            disable: 'false'
            display: 'false'
            inertial:
                inertia:
                    ixx: '0.0'
                    ixy: '0.0'
                    ixz: '0.0'
                    iyy: '0.0'
                    iyz: '0.0'
                    izz: '0.0'
                mass: '0.0'
                origin:
                    x: '0.0'
                    y: '0.0'
                    z: '0.0'
            is_frame: 'false'
            name: left_center
            scene_obj_collision: 'false'
            unprefixed_name: center
            visual_mesh_path: ''
            visual_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
        left_left_roller_back:
            collision_geometry_size: 0.0 0.0 0.0
            collision_geometry_type: box
            collision_mesh_path: ''
            collision_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
            disable: 'false'
            display: 'false'
            inertial:
                inertia:
                    ixx: '0.0'
                    ixy: '0.0'
                    ixz: '0.0'
                    iyy: '0.0'
                    iyz: '0.0'
                    izz: '0.0'
                mass: '0.0'
                origin:
                    x: '0.0'
                    y: '0.0'
                    z: '0.0'
            is_frame: 'false'
            name: left_roller_back
            scene_obj_collision: 'false'
            unprefixed_name: roller_back
            visual_mesh_path: ''
            visual_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
        left_left_roller_front:
            collision_geometry_size: 0.0 0.0 0.0
            collision_geometry_type: box
            collision_mesh_path: ''
            collision_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
            disable: 'false'
            display: 'false'
            inertial:
                inertia:
                    ixx: '0.0'
                    ixy: '0.0'
                    ixz: '0.0'
                    iyy: '0.0'
                    iyz: '0.0'
                    izz: '0.0'
                mass: '0.0'
                origin:
                    x: '0.0'
                    y: '0.0'
                    z: '0.0'
            is_frame: 'false'
            name: left_roller_front
            scene_obj_collision: 'false'
            unprefixed_name: roller_front
            visual_mesh_path: ''
            visual_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
        left_left_surface_center:
            collision_geometry_size: 0.0 0.0 0.0
            collision_geometry_type: box
            collision_mesh_path: ''
            collision_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
            disable: 'false'
            display: 'false'
            inertial:
                inertia:
                    ixx: '0.0'
                    ixy: '0.0'
                    ixz: '0.0'
                    iyy: '0.0'
                    iyz: '0.0'
                    izz: '0.0'
                mass: '0.0'
                origin:
                    x: '0.0'
                    y: '0.0'
                    z: '0.0'
            is_frame: 'false'
            name: left_surface_center
            scene_obj_collision: 'false'
            unprefixed_name: surface_center
            visual_mesh_path: ''
            visual_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
        left_left_surface_front:
            collision_geometry_size: 0.0 0.0 0.0
            collision_geometry_type: box
            collision_mesh_path: ''
            collision_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
            disable: 'false'
            display: 'false'
            inertial:
                inertia:
                    ixx: '0.0'
                    ixy: '0.0'
                    ixz: '0.0'
                    iyy: '0.0'
                    iyz: '0.0'
                    izz: '0.0'
                mass: '0.0'
                origin:
                    x: '0.0'
                    y: '0.0'
                    z: '0.0'
            is_frame: 'false'
            name: left_surface_front
            scene_obj_collision: 'false'
            unprefixed_name: surface_front
            visual_mesh_path: ''
            visual_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
    roller_back:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'false'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'false'
        name: left_roller_back
        scene_obj_collision: 'false'
        unprefixed_name: roller_back
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
    roller_front:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'false'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'false'
        name: left_roller_front
        scene_obj_collision: 'false'
        unprefixed_name: roller_front
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
    surface_center:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'false'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'false'
        name: left_surface_center
        scene_obj_collision: 'false'
        unprefixed_name: surface_center
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
    surface_front:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'false'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'false'
        name: left_surface_front
        scene_obj_collision: 'false'
        unprefixed_name: surface_front
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
lock_joints: 'false'
max_acceleration: '0.5'
max_speed: '1.0'
plugin: none
points_of_interest: []
positions:
    default_positions: initial
    joint_names: []
    positions:
        initial: []
prefix: left_
railing_height_above: '0.05'
railing_height_below: '0.0'
railing_width: '0.02'
reflect: '1'
roller_back_link: left_roller_back
roller_front_link: left_roller_front
root_link: world
srdf:
    loaded_from_cache: 'true'
    macro_path: ''
    newly_generated: 'false'
    path: /home/bam/bam_ws/src/bam_machine/bam/descriptions/urdf/conveyor/config/srdf_cache/left_conveyor_v1_v0.0.0.srdf
    xacro_path: ''
surface_center_link: left_surface_center
surface_front_link: left_surface_front
urdf:
    abs_package_dirs:
        descriptions: /home/bam/bam_ws/src/bam_machine/bam
    macro_path: /home/bam/bam_ws/src/bam_machine/bam/descriptions/urdf/conveyor/conveyor_macro.xacro
    path: ''
    xacro_path: /home/bam/bam_ws/src/bam_machine/bam/descriptions/urdf/conveyor/conveyor_config.urdf.xacro
width: '0.4'
world_rpy: 0 0 0
world_xyz: 0 0 0
