_file_name: camera_config
_file_name_stamped: camera_config_06_55pm_11_nov_2025
_metadata:
    created_at: 06_55pm_11_nov_2025
    created_by: Zach Yamaoka
    version: '1.0'
_save_dir: /home/bam/bam_ws/
color: true
fps: 30
resolution: !!python/tuple
- 1920
- 1080
