REGISTRY: {}
args:
    center_link: crab_claw_center
    disable_floating_tcp: 'false'
    opening_angles: 0.0 0.04363323129985824 0.09599310885968812 0.2007128639793479
        0.30543261909900765 0.6544984694978736 1.335176877775662
    poly_degree: '3'
    widths: 0.0 0.005 0.01 0.02 0.03 0.06 0.12
arm_mount: left_eef_link_1
bam_descriptions: /home/bam/bam_ws/src/bam_machine/bam/descriptions
base_link: base_link
base_mount: left_eef_link_1
base_rpy: 0 0 0.7853981633974483
base_xyz: 0.1 0.2 0
config_dir: /home/bam/bam_ws/src/bam_machine/bam/descriptions/urdf/crab_claw_v1/config
config_file_name: left_crab_claw_Bam_v0.0.0
config_file: /home/bam/bam_ws/src/bam_machine/bam/descriptions/urdf/crab_claw_v1/config/left_crab_claw_Bam_v0.0.0.yaml
force_srdf_gen: 'false'
hash_config_file: 'false'
info:
    config_key: ''
    name: crab_claw
    prefix: ''
    sku: Bam
    type: CrabClaw
    urdf_hash: ''
    uuid: ''
    version: 0.0.0
joints:
    eef_joint_1:
        can_id: '0'
        hardstop_position: '0.0'
        home_position: '0.0'
        initial_position: '0.0'
        limits:
            has_acceleration_limits: 'true'
            has_effort_limits: 'false'
            has_jerk_limits: 'true'
            has_position_limits: 'true'
            has_velocity_limits: 'true'
            max_acceleration: '10.0'
            max_effort: '0.0'
            max_jerk: '100.0'
            max_position: '3.141593'
            max_velocity: '10.0'
            min_acceleration: '-10.0'
            min_effort: '-0.0'
            min_jerk: '-100.0'
            min_position: '-3.141593'
            min_velocity: '-10.0'
        lock: 'false'
        lock_position: '0.0'
        mimic: 'false'
        name: left_eef_joint_1
        physics:
            damping: '0.0'
            friction: '0.0'
        transform:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        type: revolute
        unprefixed_name: eef_joint_1
    entities:
        left_left_eef_joint_1:
            can_id: '0'
            hardstop_position: '0.0'
            home_position: '0.0'
            initial_position: '0.0'
            limits:
                has_acceleration_limits: 'true'
                has_effort_limits: 'false'
                has_jerk_limits: 'true'
                has_position_limits: 'true'
                has_velocity_limits: 'true'
                max_acceleration: '10.0'
                max_effort: '0.0'
                max_jerk: '100.0'
                max_position: '3.141593'
                max_velocity: '10.0'
                min_acceleration: '-10.0'
                min_effort: '-0.0'
                min_jerk: '-100.0'
                min_position: '-3.141593'
                min_velocity: '-10.0'
            lock: 'false'
            lock_position: '0.0'
            mimic: 'false'
            name: left_eef_joint_1
            physics:
                damping: '0.0'
                friction: '0.0'
            transform:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
            type: revolute
            unprefixed_name: eef_joint_1
        left_left_joint_virtual_finger:
            can_id: '0'
            hardstop_position: '0.0'
            home_position: '0.0'
            initial_position: '0.0'
            limits:
                has_acceleration_limits: 'true'
                has_effort_limits: 'false'
                has_jerk_limits: 'true'
                has_position_limits: 'true'
                has_velocity_limits: 'true'
                max_acceleration: '10.0'
                max_effort: '0.0'
                max_jerk: '100.0'
                max_position: '3.141593'
                max_velocity: '10.0'
                min_acceleration: '-10.0'
                min_effort: '-0.0'
                min_jerk: '-100.0'
                min_position: '-3.141593'
                min_velocity: '-10.0'
            lock: 'false'
            lock_position: '0.0'
            mimic: 'true'
            name: left_joint_virtual_finger
            physics:
                damping: '0.0'
                friction: '0.0'
            transform:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
            type: revolute
            unprefixed_name: joint_virtual_finger
    joint_virtual_finger:
        can_id: '0'
        hardstop_position: '0.0'
        home_position: '0.0'
        initial_position: '0.0'
        limits:
            has_acceleration_limits: 'true'
            has_effort_limits: 'false'
            has_jerk_limits: 'true'
            has_position_limits: 'true'
            has_velocity_limits: 'true'
            max_acceleration: '10.0'
            max_effort: '0.0'
            max_jerk: '100.0'
            max_position: '3.141593'
            max_velocity: '10.0'
            min_acceleration: '-10.0'
            min_effort: '-0.0'
            min_jerk: '-100.0'
            min_position: '-3.141593'
            min_velocity: '-10.0'
        lock: 'false'
        lock_position: '0.0'
        mimic: 'true'
        name: left_joint_virtual_finger
        physics:
            damping: '0.0'
            friction: '0.0'
        transform:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        type: revolute
        unprefixed_name: joint_virtual_finger
links:
    crab_claw_center:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'false'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'true'
        name: left_crab_claw_center
        scene_obj_collision: 'false'
        unprefixed_name: crab_claw_center
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
    eef_link_1:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'true'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'false'
        name: left_eef_link_1
        scene_obj_collision: 'true'
        unprefixed_name: eef_link_1
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
    eef_link_2:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'false'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'false'
        name: left_eef_link_2
        scene_obj_collision: 'true'
        unprefixed_name: eef_link_2
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
    entities:
        left_left_crab_claw_center:
            collision_geometry_size: 0.0 0.0 0.0
            collision_geometry_type: box
            collision_mesh_path: ''
            collision_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
            disable: 'false'
            display: 'false'
            inertial:
                inertia:
                    ixx: '0.0'
                    ixy: '0.0'
                    ixz: '0.0'
                    iyy: '0.0'
                    iyz: '0.0'
                    izz: '0.0'
                mass: '0.0'
                origin:
                    x: '0.0'
                    y: '0.0'
                    z: '0.0'
            is_frame: 'true'
            name: left_crab_claw_center
            scene_obj_collision: 'false'
            unprefixed_name: crab_claw_center
            visual_mesh_path: ''
            visual_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
        left_left_eef_link_1:
            collision_geometry_size: 0.0 0.0 0.0
            collision_geometry_type: box
            collision_mesh_path: ''
            collision_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
            disable: 'false'
            display: 'true'
            inertial:
                inertia:
                    ixx: '0.0'
                    ixy: '0.0'
                    ixz: '0.0'
                    iyy: '0.0'
                    iyz: '0.0'
                    izz: '0.0'
                mass: '0.0'
                origin:
                    x: '0.0'
                    y: '0.0'
                    z: '0.0'
            is_frame: 'false'
            name: left_eef_link_1
            scene_obj_collision: 'true'
            unprefixed_name: eef_link_1
            visual_mesh_path: ''
            visual_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
        left_left_eef_link_2:
            collision_geometry_size: 0.0 0.0 0.0
            collision_geometry_type: box
            collision_mesh_path: ''
            collision_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
            disable: 'false'
            display: 'false'
            inertial:
                inertia:
                    ixx: '0.0'
                    ixy: '0.0'
                    ixz: '0.0'
                    iyy: '0.0'
                    iyz: '0.0'
                    izz: '0.0'
                mass: '0.0'
                origin:
                    x: '0.0'
                    y: '0.0'
                    z: '0.0'
            is_frame: 'false'
            name: left_eef_link_2
            scene_obj_collision: 'true'
            unprefixed_name: eef_link_2
            visual_mesh_path: ''
            visual_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
        left_left_floating_tcp_world:
            collision_geometry_size: 0.0 0.0 0.0
            collision_geometry_type: box
            collision_mesh_path: ''
            collision_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
            disable: 'false'
            display: 'true'
            inertial:
                inertia:
                    ixx: '0.0'
                    ixy: '0.0'
                    ixz: '0.0'
                    iyy: '0.0'
                    iyz: '0.0'
                    izz: '0.0'
                mass: '0.0'
                origin:
                    x: '0.0'
                    y: '0.0'
                    z: '0.0'
            is_frame: 'true'
            name: left_floating_tcp_world
            scene_obj_collision: 'false'
            unprefixed_name: floating_tcp_world
            visual_mesh_path: ''
            visual_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
        left_left_tcp_tool:
            collision_geometry_size: 0.0 0.0 0.0
            collision_geometry_type: box
            collision_mesh_path: ''
            collision_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
            disable: 'false'
            display: 'false'
            inertial:
                inertia:
                    ixx: '0.0'
                    ixy: '0.0'
                    ixz: '0.0'
                    iyy: '0.0'
                    iyz: '0.0'
                    izz: '0.0'
                mass: '0.0'
                origin:
                    x: '0.0'
                    y: '0.0'
                    z: '0.0'
            is_frame: 'true'
            name: left_tcp_tool
            scene_obj_collision: 'false'
            unprefixed_name: tcp_tool
            visual_mesh_path: ''
            visual_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
        left_left_tcp_world:
            collision_geometry_size: 0.0 0.0 0.0
            collision_geometry_type: box
            collision_mesh_path: ''
            collision_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
            disable: 'false'
            display: 'true'
            inertial:
                inertia:
                    ixx: '0.0'
                    ixy: '0.0'
                    ixz: '0.0'
                    iyy: '0.0'
                    iyz: '0.0'
                    izz: '0.0'
                mass: '0.0'
                origin:
                    x: '0.0'
                    y: '0.0'
                    z: '0.0'
            is_frame: 'true'
            name: left_tcp_world
            scene_obj_collision: 'false'
            unprefixed_name: tcp_world
            visual_mesh_path: ''
            visual_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
        left_left_virtual_finger:
            collision_geometry_size: 0.0 0.0 0.0
            collision_geometry_type: box
            collision_mesh_path: ''
            collision_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
            disable: 'false'
            display: 'false'
            inertial:
                inertia:
                    ixx: '0.0'
                    ixy: '0.0'
                    ixz: '0.0'
                    iyy: '0.0'
                    iyz: '0.0'
                    izz: '0.0'
                mass: '0.0'
                origin:
                    x: '0.0'
                    y: '0.0'
                    z: '0.0'
            is_frame: 'false'
            name: left_virtual_finger
            scene_obj_collision: 'true'
            unprefixed_name: virtual_finger
            visual_mesh_path: ''
            visual_origin:
                rpy: 0.0 -0.0 0.0
                xyz: 0.0 0.0 0.0
    floating_tcp_world:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'true'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'true'
        name: left_floating_tcp_world
        scene_obj_collision: 'false'
        unprefixed_name: floating_tcp_world
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
    tcp_tool:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'false'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'true'
        name: left_tcp_tool
        scene_obj_collision: 'false'
        unprefixed_name: tcp_tool
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
    tcp_world:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'true'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'true'
        name: left_tcp_world
        scene_obj_collision: 'false'
        unprefixed_name: tcp_world
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
    virtual_finger:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'false'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'false'
        name: left_virtual_finger
        scene_obj_collision: 'true'
        unprefixed_name: virtual_finger
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
lock_joints: 'false'
max_width: '0.1'
plugin: none
points_of_interest: []
positions:
    default_positions: initial
    joint_names: eef_joint_1 joint_virtual_finger
    positions:
        initial: 0.0 0.0
prefix: left_
reflect: '1'
root_link: world
srdf:
    loaded_from_cache: 'true'
    macro_path: ''
    newly_generated: 'false'
    path: /home/bam/bam_ws/src/bam_machine/bam/descriptions/urdf/crab_claw_v1/config/srdf_cache/left_crab_claw_Bam_v0.0.0.srdf
    xacro_path: ''
tcp_tool: left_tcp_tool
tcp_world: left_tcp_world
tcp_world_floating: left_tcp_world_floating
urdf:
    abs_package_dirs:
        descriptions: /home/bam/bam_ws/src/bam_machine/bam
    macro_path: /home/bam/bam_ws/src/bam_machine/bam/descriptions/urdf/crab_claw_v1/crab_claw_v1_macro.xacro
    path: ''
    xacro_path: /home/bam/bam_ws/src/bam_machine/bam/descriptions/urdf/crab_claw_v1/crab_claw_v1_config.urdf.xacro
world_rpy: 0 0 0
world_xyz: 0 0 0
z_into_table: 'false'
