C1_length: '0.12'
C1_mass: '0.07'
C1_thickness: '0.006'
C1_to_C2_spacing: '0.003'
C1_width: '0.03'
C2_length: '0.26'
C2_mass: '0.122'
C2_thickness: '0.006'
C2_width: '0.022'
L1_length: '0.24'
L1_mass: '0.225'
L1_offset: '0.009'
L1_to_L2_spacing: '0.009'
L1_width: '0.0508'
L2_length: '0.299658'
L2_mass: '0.228'
L2_width: '0.0381'
elbow_length: '0.12'
five_bar:
  L_c1: '0.12'
  L_c2: '0.26'
  L_elbow: '0.12'
  L_l1: '0.24'
  L_l2: '0.299658'
  L_shoulder: '0.087'
  theta_elbow_offset: '0.785398'
five_bar_offset: '0.02'
joint_info:
  c1:
    damping: '0.0'
    friction: '0.0'
  c2:
    damping: '0.0'
    friction: '0.0'
  joint_1:
    damping: '0.0'
    friction: '0.0'
  joint_2:
    damping: '0.0'
    friction: '0.0'
  joint_3:
    damping: '0.0'
    friction: '0.0'
  joint_4:
    damping: '0.0'
    friction: '0.0'
  joint_5:
    damping: '0.0'
    friction: '0.0'
  joint_6:
    damping: '0.0'
    friction: '0.0'
link_density: '2700.0'
link_wall_thickness: '0.001587'
shoulder_C1_offset: '0.0505'
shoulder_J2_offset: '0.1375'
shoulder_driver_length: '0.021'
shoulder_front_plate_offset: '0.05'
shoulder_gearbox_diameter: '0.065'
shoulder_gearbox_flange_diameter: '0.086'
shoulder_gearbox_front_offset: '0.019'
shoulder_gearbox_length: '0.0815'
shoulder_gearbox_mass: '1.266'
shoulder_motor_length: '0.055'
shoulder_motor_mass: '0.738'
shoulder_motor_width: '0.06'
shoulder_mount_plate_thickness: '0.006'
shoulder_plate_thickness: '0.003'
theta_elbow_offset: '0.785398'
wrist_driver_length: '0.016'
wrist_front_offset: '0.003'
wrist_length: '0.06'
wrist_pipe_density: '2700.0'
wrist_pipe_diameter: '0.037'
wrist_pipe_mass: '0.0315'
wrist_pipe_wall_thickness: '0.0015'
wrist_servo_diameter: '0.053'
wrist_servo_length: '0.026'
wrist_servo_mass: '0.22'
wrist_to_wrist_spacing: '0.001'
